### ISSUE TITLE
PyCharm 2021.1 broke Iceberg

### ISSUE THREAD

**Issue by spyroot** [milankinen/intellij-iceberg-theme#1]
Hi Folks,

Looks like PyCharm 2021.1 broken IceBerg :(.

Error. Plugin 'Iceberg' (version '0.3.0') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is PY-211.6693.115

Thank you.

**Comment by milankinen** [comment]
Thanks for reporting! I'll investigate this later tonight.

**Comment by milankinen** [comment]
I released version [`0.4.0`](https://plugins.jetbrains.com/plugin/15126-iceberg/versions/stable/116252) that should work with the new 2021.1 versions. It should be reviewed by JetBrains in few days. Meanwhile you can either download the plugin as zip from the GH releases or from the direct download link I wrote above.

**Comment by spyroot** [comment]
Just tested. and amazing iceberg back : ))) thank very much
