### ISSUE TITLE
Search term not visible in structure panel

### ISSUE THREAD

**Issue by mpgr04** [milankinen/intellij-iceberg-theme#2]
When using the theme I noticed that the text to search for is not visible in the structures panel, but otherwise a terrific theme!

I have added a screenshot where the problem is apparent.

This is how it looks with the default Darcula theme
![image](https://user-images.githubusercontent.com/34566496/121916419-687dcb00-cd34-11eb-9f1e-3d568a85b9e1.png)

And this is how it looks with iceberg
![image](https://user-images.githubusercontent.com/34566496/121916544-86e3c680-cd34-11eb-8cb5-7602a422e31b.png)

**Comment by milankinen** [comment]
Thanks! I'll check this tomorrow evening.

**Comment by milankinen** [comment]
Sorry to keep you waiting, I've been very busy this week. 😞  

I fixed this and released it in the version [`0.5.0`](https://plugins.jetbrains.com/plugin/15126-iceberg/versions/stable/123117) among few other small improvements. It should be reviewed by JetBrains in few days. Meanwhile you can either download the plugin as zip from the GH releases or from the direct download link I wrote above. 

Cheers!

**Comment by mpgr04** [comment]
Cool, Thank you!

Keep up the great work!
