### ISSUE TITLE
Not compatible with WebStorm 2021.2

### ISSUE THREAD

**Issue by griff73** [milankinen/intellij-iceberg-theme#3]
This is by far my favourite theme for WebStorm, but unfortunately the theme was automatically deactivated following update to the latest version of WebStorm (2021.2) due to not being compatible with this release.

**Comment by milankinen** [comment]
Thanks for reporting! This will be fixed in [`0.6.0`](https://github.com/milankinen/intellij-iceberg-theme/releases/tag/v0.6.0) which will be available in few days until JetBrains staff has reviewed it. Meanwhile you can install the compatible plugin version directly from the release artifact zip.

**Comment by griff73** [comment]
@milankinen Thank you very much for the fix, it's very much appreciated.
